name: pdf_reader
description: A PDF Reader App (Flutter + GetX + MVC)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # PDF Viewer (Flutter 3.32 compatible)
  pdfx: ^2.6.0

  # File Picker
  file_picker: 8.3.7

  # Local Storage
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/pdf/book.pdf